version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    volumes:
      - ./docker/data/vault/config:/vault/config
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "easy"
    ports:
      - 8200:8200
      - 8201:8201
    depends_on:
      - consul
    cap_add:
      - IPC_LOCK
    links:
      - consul
    entrypoint: vault server -dev -log-level=trace -config /vault/config/vault-config.json

  consul:
    image: consul:1.15
    container_name: consul
    volumes:
      - ./docker/data/consul/data:/consul/data
      - ./docker/data/consul/config:/consul/config
    ports:
      - 8500:8500

  setup:
    image: vault:1.13.3
    container_name: setup
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "easy"
    depends_on:
      - vault
    links:
      - vault
    entrypoint: vault kv put secret/gs-vault-config example.username=demouser example.password=demopassword


