version: '3.8'

services:
  vault:
    image: vault:1.13.3
    volumes:
      - ./docker/data/vault/config:/vault/config
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: http://vault:8200
      VAULT_DEV_ROOT_TOKEN_ID: dev-only-token # allow full root access to anyone who presents a token with the specified value
      VAILT_LOCAL_CONFIG: "{\"backend\":{\"consul\":{\"address\":\"consul:8500\",\"path\":\"vault\"}}}"
    ports:
      - 8200:8200
      - 8201:8201
    depends_on:
      - consul
    cap_add:
      - IPC_LOCK
    links:
      - consul
    entrypoint: vault server -config=/vault/config/vault-config.json

  consul:
    image: consul:1.15
    volumes:
      - ./docker/data/consul/data:/consul/data
      - ./docker/data/consul/config:/consul/config
    ports:
      - 8500:8500
